name: Run a notebook in the current repo on PR

on:
  pull_request:

env:
  DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}

jobs:
  repos-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Setup Databricks environment
        uses: databrickslabs/setup-databricks-cli@v0
        with:
          token: ${{ secrets.DATABRICKS_TOKEN }}
          url: ${{ secrets.DATABRICKS_URL }}

      - name: Create Databricks job
        run: |
          # Create the Databricks job and capture the job ID
          job_id=$(databricks jobs create --json '{
            "name": "MyDatabricksJob",
            "new_cluster": {
              "num_workers": 2, // Specify the number of workers
              "node_type_id": "Standard_D3_v2" // Specify the node type
            },
            "notebook_task": {
              "notebook_path": "/path/to/your/notebook"
            }
          }' | jq -r '.job_id')

          echo "Databricks Job ID: $job_id"

      - name: Run Databricks job
        run: |
          # Run the Databricks job by job ID
          databricks jobs run-now --job-id $job_id

      - name: Delete Databricks job
        run: |
          # Delete the Databricks job by job ID
          databricks jobs delete --job-id $job_id