name: Databricks CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Databricks CLI
      run: |
        pip install databricks-cli

    - name: Deploy to Databricks
      run: |
        databricks workspace import_dir notebooks /Workspace/databricks-project